a=input('digite algo ')
print('O tipo primitivo desse valor é :',type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Esta em maiusculas? ',a.isupper())
print('Esta em minusculas? ',a.islower())
print('Esta capitalizada? ',a.istitle())
